<h1><center>Laboratorio 3: El Pandas no muerde (act. I) 🐼</center></h1>

<center><strong>MDS7202: Laboratorio de Programación Científica para Ciencia de Datos</strong></center>

---

### Cuerpo Docente

- Profesores: Pablo Badilla y Diego Cortez
- Auxiliares: Valentina Rojas y Melanie Peña
- Ayudantes: Javiera Arévalo, Tamara Carrasco y Ignacio Reyes

### Equipo: SUPER IMPORTANTE - notebooks sin nombre no serán revisados

- Nombre de alumno 1: Javiera Romero Orrego
- Nombre de alumno 2: Patricio Espinoza A.

---

### Reglas

- **Grupos de 2 personas**
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente serán respondidos por este medio.
- Prohibido copiar.
- Uso de LLM (Copilot, Claude, Antigravity, Cursor, etc.) restringido a consultas, documentación y corrección de errores.

### Objetivos

- Entender, aplicar y aprovechar las ventajas que nos ofrece la libreria `pandas` para manejar datos tabulares.
- Aprender a utilizar la documentación de pandas (y en general, de cualquier librería de python) como también a buscar soluciones en la web.

> ⚠️ **Importante**: El laboratorio deberá ser desarrollado sin el uso de iteradores nativos de python (aka "for", "while"). La idea es que aprendan a exprimir al máximo las funciones optimizadas que nos entrega `pandas`.

### Librerias utiles para el Lab 😸

In [1]:
!uv install pandas plotly

error: unrecognized subcommand 'install'

  tip: a similar subcommand exists: 'uv pip install'

Usage: uv [OPTIONS] <COMMAND>

For more information, try '--help'.

In [2]:
import pandas as pd
import plotly.express as px

---

# 1. Rendimiento en Estudiantes 📚

### 📊 Sobre los datos

El objetivo principal será realizar un trabajo de limpieza y preparación de datos utilizando exclusivamente DataFrames y las herramientas asociadas a estos. 

Para esto deberán trabajar con el dataset `students_grades.json`, el cual pueden descargar desde la siguiente URL:

> https://raw.githubusercontent.com/MDS7202/MDS7202/refs/heads/main/recursos/2026-01/labs/lab3/students_grades.json

El dataset contiene información sobre el rendimiento de alumnos en distintos ramos. Cada fila representa un estudiante con las siguientes columnas:

- `names`: Nombre del estudiante
- `gender`: Género
- `race/ethnicity`: Grupo étnico
- `parental level of education`: Nivel educacional de los padres
- `lunch`: Tipo de almuerzo (estándar o reducido)
- `test preparation course`: Si completó curso de preparación
- `math score`: Nota de matemáticas (escala 0-100)
- `reading score`: Nota de lectura (escala 0-100)
- `writing score`: Nota de escritura (escala 0-100)


**Nota sobre GPA**: En el contexto educativo anglosajón, GPA (*Grade Point Average*) se refiere al promedio general de calificaciones.

---

## 1.1 Revisión de datos 🔎 [1.2 puntos]

<p align="center">
  <img src="https://media2.giphy.com/media/4FQMuOKR6zQRO/giphy.gif?cid=ecf05e47ii9lhu9tc9tb31d6lafrysp2zyf6u8w3y348mk8t&rid=giphy.gif&ct=g">
</p>

*Don Caguayo*, rector de la Universidad de la Cachaña, les comenta que actualmente la Universidad no tiene una subdirección de análisis de datos, pero que tiene interés en formar una. Es por esto, que se contacta con ud. y su equipo para iniciar de forma exploratoria diversas tareas de análisis y consolidación de datos respectivos al rendimiento de sus alumnos.

En su primera reunión, el rector les comenta que la sección de TI posee una base de datos con más de **1000** filas, en donde cada fila representa un alumno matriculado. Sin embargo, cree fuertemente que existen errores en esta: solo tiene registro de **1000** matriculas. Por este motivo, especula que se han realizado malas prácticas al inscribir dichos datos.


En consecuencia, el rector les solicita a ustedes como tarea inicial que exploren la base de datos y encuentre posibles falencias dentro de sus registros. Para esto, usted debe estar al tanto que las notas (GPA) están en una escala que van del **0 al 100** (porcentaje de logro) y **no es posible que un alumno aparezca más de una vez, ya que las notas son promedios de sus asignaturas**. 

Cualquier alumno que posea un valor diferente a esta escala, debería ser eliminado de la base de datos.

> **Instrucciones**

Implemente la función `analyze_df` que tome un `DataFrame` y que le permita generar diversos análisis que permitan observar estadísticas y anomalías de las diferentes variables que componen este dataset.

**To-Do**
1. [ ] Imprimir un mensaje con las dimensiones del Dataframe. [0.1 puntos]
2. [ ] Imprimir un mensaje con los nombres de las columnas que conforman el DataFrame. [0.1 puntos]
3. [ ] Mostrar los primeros 5, los últimos 5 elementos del DataFrame y realice un muestreo de 5 elementos de forma aleatoria. [0.1 puntos]
4. [ ] Mostrar una descripción rápida de las variables numéricas del DataFrame (utilice un método visto en clases). [0.1 puntos]
5. [ ] Imprimir un mensaje con la cantidad de valores nulos (investigue el método `isna()` y `sum()` de los DataFrames). [0.1 puntos]
6. [ ] Imprimir un mensaje que detalle la cantidad de valores unicos (investigue `nunique()`) . [0.1 puntos]
7. [ ] Imprimir un mensaje con el total de filas que contengan nombres duplicados (investigue `duplicated()` y su parámetro `subset`). [0.1 puntos]
8. [ ] Mostrar las filas que contengan nombres sean duplicados (investigue `duplicated()` y su parámetro `subset`). [0.1 puntos]
9. [ ] A través de `px.histogram(col_name, title="Título").show()` graficar el histograma de cada tipo de nota (`math score`, `reading score`, `writing score`). Investigue cómo funcionan los histogramas si es necesario. [0.2 puntos]
10. [ ] Responda las preguntas en la celda correspondiente. [0.2 puntos]

> **Nota:** Para imprimir utilice `print(...)`. Para mostrar `DataFrames`, utilice `display(...)` ya que este permite mostrar estos elementos como tablas.

> **Nota 2:** Utilice la documentación de [pandas](https://pandas.pydata.org/docs/index.html) como también StackOverflow para resolver cualquier problema o inconveniente.

**Respuesta Código:**

In [3]:
# Primero deberan cargar los datos usando un lector apropiado
df_grades = pd.read_json("students_grades.json")

In [4]:
df_grades

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,Rita Courtney,female,group B,some high school,standard,none,37,46,46
1,Madeline Fuller,female,group C,some high school,standard,none,124,142,142
2,Daniel Rester,male,group E,associate's degree,standard,none,156,196,193
3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,80,78,81
4,Geraldine Hale,female,group A,associate's degree,standard,none,131,166,166
...,...,...,...,...,...,...,...,...,...
1395,Alexander Dillon,male,group D,associate's degree,standard,none,193,142,193
1396,Marina Zeigler,female,group C,bachelor's degree,free/reduced,completed,66,74,81
1397,Laurie Carter,female,group B,some high school,standard,completed,54,61,62
1398,Joseph Mccoy,male,group D,some college,free/reduced,none,193,196,193
1399,Amanda Perez,female,group A,high school,standard,completed,68,80,76

In [5]:
display(df_grades.head())

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,Rita Courtney,female,group B,some high school,standard,none,37,46,46
1,Madeline Fuller,female,group C,some high school,standard,none,124,142,142
2,Daniel Rester,male,group E,associate's degree,standard,none,156,196,193
3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,80,78,81
4,Geraldine Hale,female,group A,associate's degree,standard,none,131,166,166

In [ ]:
def analyze_df(df: pd.DataFrame) -> None:
    df_copy = df.copy()
    # 1. Dimensiones del datframe
    print(f"1. Dimensiones del dataframe: Largo: {df_copy.shape[0]}, Ancho: {df_copy.shape[1]}\n")

    # 2. Nombres de las columnas
    print(f"2. Nombres de las columnas: {df_copy.columns.tolist()}\n")

    # 3.1 Primeros 5 elementos del dataframe
    print("3.1. Primeros 5 elementos del dataframe:")
    display(df_copy.head())

    # 3.2 Ultimos 5 elementos del dataframe
    print("3.2. Ultimos 5 elementos del dataframe:")
    display(df_copy.tail())

    # 3.3 5 elementos aleatorios del dataframe
    print("3.3. 5 elementos aleatorios del dataframe:")
    display(df_copy.sample(5, random_state=42))

    # 4. Descripción de las variables númericas del dataframe
    print("4. Descripción de las variables númericas del dataframe:")
    display(df_copy.describe())

    # 5. Cantidad de valores nulos por columna  #NOTA: Aqui no se consideran aquellos que dice 'none'
    print("5. Cantidad de valores nulos por columna:")
    print(f"{df_copy.isna().sum()}\n")

    print("5.1 Cantidad de filas que tienen al menos un valor nulo:")
    print(f"{df_copy.isna().any(axis=1).sum()}\n")

    # 6. Cantidad de valores unicos (filas distintas unicas)
    print("6. Cantidad de valores unicos por columna:")
    print(f"{df_copy.nunique()}\n")

    # 7. Cantidad de filas cuyos nombres esten duplicados
    print("7. Cantidad de filas cuyos nombres esten duplicados:")
    print(f"{df_copy.duplicated(subset=['names']).sum()}\n")

    # 8. Imprimir las filas cuyos nombres esten duplicados
    print("8. Filas cuyos nombres esten duplicados:")
    # keep=False permite mostrar todos los duplicados
    display(df_copy[df_copy.duplicated(subset=["names"], keep=False)])

    # 9. Graficar el histograma de cada tipo de nota (`math score`, `reading score`, `writing score`)
    if "math score" in df_copy.columns and "reading score" in df_copy.columns and "writing score" in df_copy.columns:
        for col in ["math score", "reading score", "writing score"]:
            fig = px.histogram(df_copy, x=col, title=f"Histograma de {col}")
            fig.show()
    else:
        for col in ["math_score", "reading_score", "writing_score"]:
            fig = px.histogram(df_copy, x=col, title=f"Histograma de {col}")
            fig.show()

    return 0

In [7]:
analyze_df(df_grades)

1. Dimensiones del dataframe: Largo1400, Ancho: 9

2. Nombres de las columnas: ['names', 'gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'math score', 'reading score', 'writing score']

3.1. Primeros 5 elementos del dataframe:

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,Rita Courtney,female,group B,some high school,standard,none,37,46,46
1,Madeline Fuller,female,group C,some high school,standard,none,124,142,142
2,Daniel Rester,male,group E,associate's degree,standard,none,156,196,193
3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,80,78,81
4,Geraldine Hale,female,group A,associate's degree,standard,none,131,166,166

3.2. Ultimos 5 elementos del dataframe:

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
1395,Alexander Dillon,male,group D,associate's degree,standard,none,193,142,193
1396,Marina Zeigler,female,group C,bachelor's degree,free/reduced,completed,66,74,81
1397,Laurie Carter,female,group B,some high school,standard,completed,54,61,62
1398,Joseph Mccoy,male,group D,some college,free/reduced,none,193,196,193
1399,Amanda Perez,female,group A,high school,standard,completed,68,80,76

3.3. 5 elementos aleatorios del dataframe:

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
665,Bonnie Williams,female,group A,some high school,standard,completed,193,196,97
624,Marcia York,female,group D,bachelor's degree,free/reduced,none,63,73,78
115,Francisco Johnson,male,group B,associate's degree,standard,completed,82,84,78
478,Edward Lowman,male,group E,associate's degree,free/reduced,completed,91,73,80
233,Thomas Simmons,male,group C,bachelor's degree,standard,completed,131,171,196

4. Descripción de las variables númericas del dataframe:

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
count,1400,1400,1400,1400,1400,1400,1400,1400,1400
unique,1153,2,5,6,2,2,97,89,93
top,Robert Frazier,female,group C,some college,standard,none,193,193,193
freq,3,723,452,334,904,898,120,117,133

5. Cantidad de valores nulos por columna:
names                          0
gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

5.1 Cantidad de filas que tienen al menos un valor nulo:
0

6. Cantidad de valores unicos por columna:
names                          1153
gender                            2
race/ethnicity                    5
parental level of education       6
lunch                             2
test preparation course           2
math score                       97
reading score                    89
writing score                    93
dtype: int64

7. Cantidad de filas cuyos nombres esten duplicados:
247

8. Filas cuyos nombres esten duplicados:

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,Rita Courtney,female,group B,some high school,standard,none,37,46,46
5,Brian Young,male,group C,some high school,standard,none,73,66,63
6,Howard Jimenez,male,group E,some high school,standard,completed,81,75,76
8,Jonathan Clingan,male,group D,some college,standard,completed,71,61,69
10,Nancy Bassett,female,group C,high school,standard,none,124,196,193
...,...,...,...,...,...,...,...,...,...
1385,James Crawford,male,group D,master's degree,standard,none,193,147,131
1390,Gloria Bradford,female,group B,high school,standard,none,124,64,193
1393,Adam Romero,male,group C,high school,standard,completed,124,193,49
1395,Alexander Dillon,male,group D,associate's degree,standard,none,193,142,193
1398,Joseph Mccoy,male,group D,some college,free/reduced,none,193,196,193

0

**Preguntas ❓:**

> ¿Qué anomalías es posible observar de los datos que componen el DataFrame? 

> ¿Existen valores nulos o duplicados? ¿Qué puede interpretar de la distribución de las notas en los histogramas?

**Respuestas 📝:**

```
1. Hay anomalías observables dentro de los scores de math, reading y writing puesto que la escala de GPA es de 0 a 100, y muchos estudiantes tienen puntajes sobre 100. Asimimo, de la cantidad de filas con nombres duplicados podemos notar que 247 estudiantes estan repetidos lo cual no debería ser posible.

2. Dentro del análisis realizado no parecen encontrarse nulos, sin embargo, al ver los datos es posible observar que se utiliza 'none' como nomenclatura para este tipo de dato, lo que sugiere una falta de información presente, y una anomalía en el formato de los datos. Duplicados existen tanto en filas como en nombres de los estudiantes, presentando otro tipo de anomalía.

En cuanto a los histogramas, las distribuciones de notas entre los intervalos [0, 100] siguen una distribución normal típica en evaluaciones, pero en aquellos datos (anomalías) que superan los 100 puntos se puede observar que se pierde la forma de la distribución. En particular, para puntajes sobre 100 se presentan 3 peaks que se repiten para reading, writing y math: 120-129, 140-149 y 190-199.
```

---

## 1.2 Limpieza de Datos 🫧

<p align="center">
  <img src="https://media3.giphy.com/media/c09yGbnSyaFRS/giphy.gif?cid=ecf05e47d0ejjjnpfj0ywcbwz7zk7sw2rfdpis890gmdpvj2&rid=giphy.gif&ct=g">
</p>

¡Bien! Ya identificaron las anomalías. Ahora es momento de poner manos a la obra y limpiar esos datos. 🧹

En base a lo realizado anteriormente, realice una limpieza del dataset. Asuma los supuestos señalados en la pregunta anterior para limpiar el DataFrame y cree una función que le permita limpiar los datos. Una vez limpiado, compruebe nuevamente los datos con la función creada en la sección 1.1.

**To-Do:**

- [ ] Crear función que permita limpiar el dataset.
  - [ ] Cambiar el nombre de las columnas a snake case (Hint: implementar util `to_snake_case` usando métodos de strings + list/dict comprehension). [0.1 puntos]
  - [ ] Eliminar la palabra `race` de la columna `race/ethnicity` (Hint: `rename`) [0.1 puntos]
  - [ ] Eliminar datos duplicados [0.2 puntos]
  - [ ] Forzar tipos de las columnas con score a float con `pd.to_numeric, errors="coerce")` (Hint: coerce dejará como nulos los valores que no sean floats, importante para el siguiente paso)[0.2 puntos]
  - [ ] Eliminar datos nulos [0.2 puntos]
  - [ ] Eliminar registros con notas anómalas (> 100, < 0) [0.2 puntos]
- [ ] Comprobar que ya no existen anomalías en los datos usando la función de la sección 1.1 (solo imprimir, no justificar). Puede que necesite adaptar la función para usar los nuevos nombres de columnas

**Respuesta:**

In [8]:
def to_snake_case(s: str) -> str:
    """Transforma un string a snake_case:
    los espacios se reemplazan por guiones bajos y todas las letras se convierten a minúsculas."""
    return s.lower().replace(" ", "_")

In [9]:
def clean_data(df: pd.DataFrame) -> pd.DataFrame:
    # 1. Renombrar las columnas a snake_case
    df.columns = [to_snake_case(col) for col in df.columns]

    # 2. Eliminar race/ de la columna race/ethnicity
    df.rename(columns={"race/ethnicity": "ethnicity"}, inplace=True)

    # 3. Eliminar duplicados
    df.drop_duplicates(inplace=True)

    # 4. Pasar a float las columnas de notas con coerce
    for col in ["math_score", "reading_score", "writing_score"]:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    # 5. Eliminar filas con valores nulos en las columnas de notas
    df.dropna(inplace=True)  # Los 'none' como str no se eliminarian

    # 6. Eliminar registros con notas anomalas (menores a 0 o mayores a 100)
    for col in ["math_score", "reading_score", "writing_score"]:
        df = df[(df[col] >= 0) & (df[col] <= 100)]

    return df

In [10]:
df_cleaned = clean_data(df_grades)
df_cleaned

,names,gender,ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,Rita Courtney,female,group B,some high school,standard,none,37.0,46.0,46.0
3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,80.0,78.0,81.0
5,Brian Young,male,group C,some high school,standard,none,73.0,66.0,63.0
6,Howard Jimenez,male,group E,some high school,standard,completed,81.0,75.0,76.0
7,Wayne Wilson,male,group B,some high school,standard,completed,94.0,86.0,87.0
...,...,...,...,...,...,...,...,...,...
1392,Richard Young,male,group D,high school,standard,none,69.0,75.0,71.0
1394,Wanda Russell,female,group B,high school,free/reduced,completed,23.0,44.0,36.0
1396,Marina Zeigler,female,group C,bachelor's degree,free/reduced,completed,66.0,74.0,81.0
1397,Laurie Carter,female,group B,some high school,standard,completed,54.0,61.0,62.0
1399,Amanda Perez,female,group A,high school,standard,completed,68.0,80.0,76.0

In [11]:
analyze_df(df_cleaned)

1. Dimensiones del dataframe: Largo1000, Ancho: 9

2. Nombres de las columnas: ['names', 'gender', 'ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course', 'math_score', 'reading_score', 'writing_score']

3.1. Primeros 5 elementos del dataframe:

,names,gender,ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,Rita Courtney,female,group B,some high school,standard,none,37.0,46.0,46.0
3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,80.0,78.0,81.0
5,Brian Young,male,group C,some high school,standard,none,73.0,66.0,63.0
6,Howard Jimenez,male,group E,some high school,standard,completed,81.0,75.0,76.0
7,Wayne Wilson,male,group B,some high school,standard,completed,94.0,86.0,87.0

3.2. Ultimos 5 elementos del dataframe:

,names,gender,ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
1392,Richard Young,male,group D,high school,standard,none,69.0,75.0,71.0
1394,Wanda Russell,female,group B,high school,free/reduced,completed,23.0,44.0,36.0
1396,Marina Zeigler,female,group C,bachelor's degree,free/reduced,completed,66.0,74.0,81.0
1397,Laurie Carter,female,group B,some high school,standard,completed,54.0,61.0,62.0
1399,Amanda Perez,female,group A,high school,standard,completed,68.0,80.0,76.0

3.3. 5 elementos aleatorios del dataframe:

,names,gender,ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
750,Stephen Broenneke,male,group B,some college,standard,none,54.0,52.0,51.0
1039,Donald Greenberg,male,group C,associate's degree,standard,none,46.0,43.0,42.0
1044,Karen Wagaman,female,group B,associate's degree,standard,none,80.0,86.0,83.0
938,Brenna Pate,female,group A,bachelor's degree,standard,none,51.0,49.0,51.0
586,Larry Torres,male,group D,associate's degree,free/reduced,none,53.0,54.0,48.0

4. Descripción de las variables númericas del dataframe:

       math_score  reading_score  writing_score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

5. Cantidad de valores nulos por columna:
names                          0
gender                         0
ethnicity                      0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64

5.1 Cantidad de filas que tienen al menos un valor nulo:
0

6. Cantidad de valores unicos por columna:
names                          1000
gender                            2
ethnicity                         5
parental_level_of_education       6
lunch                             2
test_preparation_course           2
math_score                       81
reading_score                    72
writing_score                    77
dtype: int64

7. Cantidad de filas cuyos nombres esten duplicados:
0

8. Filas cuyos nombres esten duplicados:

Empty DataFrame
Columns: [names, gender, ethnicity, parental_level_of_education, lunch, test_preparation_course, math_score, reading_score, writing_score]
Index: []

0

> Utilice la función creada en el punto 1.1 para verificar sus resultados. Adapte los nombres de las columnas con snake_case si es necesario.

In [12]:
print(f"Filas finales: {df_cleaned.shape[0]}")

Filas finales: 1000

**✅ Checkpoint**: Después de la limpieza deberías tener exactamente 1000 filas

---

## 1.3 Creando y Estructurando Datos 📊



<p align="center">
  <img src="https://media4.giphy.com/media/ko7twHhomhk8E/giphy.gif?cid=ecf05e47xmgfz8ftaom8saa4cwktxpb0fkui9yk3nakb4ff1&rid=giphy.gif&ct=g">
</p>

¡Perfecto! Ya tenemos datos limpios y confiables. Ahora Don Caguayo quiere que le ayudemos a generar nuevas columnas y realizar análisis más profundos. 📊

---

### 1.3.1 Transformación de notas a "Nota Chilena" 🇨🇱

En una de las reuniones con Don Caguayo, este les comenta su intención de pasar todas sus notas a la "Escala Chilena". Para esto les facilita la siguiente ecuación:

$$Nota \, Chilena= \% \, de \, logro \times 0.06 + 1$$

Utilizando la ecuación entregada, cree una función que le permita transformar las notas (que están en escala 0-100) a la escala chilena [1,7] y entregue las notas redondeadas al segundo decimal.

**To-Do**

- [ ] Implementa la función `to_chilean_grade` que toma un **DataFrame** y el nombre de una **columna** con notas en escala 0-100, y retorna una **Serie** con las notas transformadas a escala chilena (rango 1.0-7.0). [0.3 puntos]
- [ ] Agrega las nuevas series de notas de matemáticas (columna `math_score_cl`), lectura (columna `reading_score_cl`) y escritura (columna `writing_score_cl`) al dataframe `df_cleaned`. [0.3 puntos]

**Respuesta Código:**

In [13]:
# En esta celda implementa la operación solicitada
def to_chilean_grade(df: pd.DataFrame, columna: str) -> pd.Series:
    """Se deben crear tres nuevas columnas, la funcion to_chilean_grade recibe el dataframe y
    el nombre de una columna y retorna una serie de pandas con esa serie de pandas con esa columna transformada"""

    nota_chilena = df[columna].apply(lambda x: x * 0.06 + 1)
    return nota_chilena

In [14]:
# En esta celda ejecuta la función y luego usa indexadores para agregar las nuevas columnas al dataframe limpio
math_chilean = to_chilean_grade(df_cleaned, "math_score")
writing_chilean = to_chilean_grade(df_cleaned, "writing_score")
reading_chilean = to_chilean_grade(df_cleaned, "reading_score")

# Indexador para agregar las nuevas columnas al dataframe limpio
df_cleaned["math_score_cl"] = math_chilean
df_cleaned["writing_score_cl"] = writing_chilean
df_cleaned["reading_score_cl"] = reading_chilean

---

### 1.3.2 Promedios 📋 [0.3 puntos]

Con todas las notas transformadas, la prestigiosa Universidad De la Cachaña necesita obtener el promedio general (GPA) de cada uno de los alumnos. Para esto se le solicita que calcule el promedio de las tres asignaturas y lo anexe como una nueva columna al DataFrame. 

Cabe señalar que las notas promedio deben ser **redondeadas** al segundo decimal.

**To-Do:**
- [ ] Implementa la función `calculate_average` que dado un dataframe con las notas por alumno, calcula y retorna dos **Series**: una con el promedio de las notas originales (escala 0-100) y otra con el promedio de las notas chilenas.
- [ ] Ejecuta la función y luego, usando indexadores apropiados, agrega las columnas `mean` (promedio escala 0-100) y `mean_cl` (promedio escala chilena) a `df_cleaned`.

**Respuesta:**

In [15]:
# En esta celda implementa la operación solicitada
def calculate_average(df: pd.DataFrame) -> tuple[pd.Series, pd.Series]:
    """Comprobar que existen las columnas math_score_cl, writing_score_cl y reading_score_cl,
    luego calcular el promedio de estas tres columnas para cada fila y retornar una serie de pandas con el resultado
    Retorna dos series:
        - Una con el promedio de las notas originales
        - Otra con el promedio de las notas chilenas
    """
    if not all(col in df.columns for col in ["math_score_cl", "writing_score_cl", "reading_score_cl"]):
        raise ValueError(
            "Las columnas math_score_cl, writing_score_cl y reading_score_cl deben existir en el dataframe"
        )

    promedio_original = df[["math_score", "writing_score", "reading_score"]].mean(axis=1)
    promedio_chileno = df[["math_score_cl", "writing_score_cl", "reading_score_cl"]].mean(axis=1)

    return promedio_original, promedio_chileno

In [16]:
# En esta celda ejecuta la función y luego usa indexadores para agregar la nueva columna al dataframe limpio
promedio_original, promedio_chileno = calculate_average(df_cleaned)

# Indexador para agregar la nueva columna al dataframe limpio
df_cleaned["mean"] = promedio_original
df_cleaned["mean_cl"] = promedio_chileno

---

### 1.3.3 Rankings 📶 [0.4 puntos]

¡Excelente trabajo calculando los promedios! Ahora Don Caguayo quiere saber quiénes son los estudiantes top y generar un ranking general.

**To-Do:**
- [ ] Implementa la función `rank_students` que dado un dataframe con las notas por alumno, obtiene una **Serie** con el ranking de alumnos, de mejor a peor nota (usando el promedio chileno `mean_cl`).
- [ ] Ejecuta la función y luego, usando indexadores apropiados, agrega la columna `rank` al `df_cleaned`.

In [17]:
# En esta celda implementa la operación solicitada
def rank_students(df: pd.DataFrame) -> pd.Series:
    """
    Genera el ranking como serie de pandas para indexarlo luego al dataframe limpio, el ranking se debe generar a partir de la columna mean_cl
    """
    if "mean_cl" not in df.columns:
        raise ValueError("La columna mean_cl debe existir en el dataframe")

    # Generar ranking
    ranking = df["mean_cl"].rank(ascending=False, method="min").astype(int)

    return ranking

In [18]:
# En esta celda ejecuta la función y luego usa indexadores para agregar la nueva columna al dataframe limpio
ranking = rank_students(df_cleaned)
# Indexador para agregar la nueva columna al dataframe limpio
df_cleaned["rank"] = ranking

In [19]:
df_cleaned.sort_values("rank").head()

,names,gender,ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,math_score_cl,writing_score_cl,reading_score_cl,mean,mean_cl,rank
384,Elizabeth Beasley,female,group E,bachelor's degree,standard,none,100.0,100.0,100.0,7.00,7.0,7.0,100.000000,7.00,1
1352,Sandra Pompey,female,group E,associate's degree,standard,none,100.0,100.0,100.0,7.00,7.0,7.0,100.000000,7.00,1
677,Richard Pryor,male,group E,bachelor's degree,standard,completed,100.0,100.0,100.0,7.00,7.0,7.0,100.000000,7.00,1
475,Emma Gray,female,group E,bachelor's degree,standard,completed,99.0,100.0,100.0,6.94,7.0,7.0,99.666667,6.98,4
279,Emma Brasher,female,group D,some high school,standard,completed,97.0,100.0,100.0,6.82,7.0,7.0,99.000000,6.94,5

**Preguntas ❓:**


1. ¿Qué pasa si hay alumnos con el mismo promedio? 
2. ¿Cómo se debería manejar el ranking en ese caso? 
3. ¿Qué parámetro deberían configurar? 
 
4. ¿Cuál es el comportamiento por defecto?

**Respuestas 📝:**

```
1. Si hay alumnos con el mismo promedio (empate), quedarán todos con la posición más alta disponible (Siendo el '1' el más alto). Esto ocurre debido al method='min'

2. El caso actualmente se maneja bien con method='min' ya que con 'average' los top 3 quedarían con posición 2, mientras que con 'max' los top 3 quedarían con posición 3.

3. El parámetro method es el que se debe configurar en caso de querer cambiar como se maneja el ranking en casos de empate

4. El comportamiento por defecto es el average, el cual ve el promedio de los ranks que hubieran tenido las posiciones empatadas y se las asigna a los empatados (Por ejemplo un empate de las posiciones 1, 2 y 3 tiene como promedio '2', y esta es asignada a esas 3 personas).
```

---

### 1.3.4 Reprobados y Destacados 🏅

Contentos con su desempeño, la Universidad les solicita que identifiquen a los alumnos que han reprobado el año y a los que han tenido un desempeño destacado.

Para esto se considerará que:
- Un alumno ha **reprobado** cuando el promedio de notas chilenas (`mean_cl`) es inferior a 4.0
- Un alumno es **destacado** si posee notas chilenas superiores a 6.0 en `math_score_cl` y superiores a 6.3 en `reading_score_cl` y `writing_score_cl`


Cree las siguientes funciones:

1. [ ] `extract_failing` que retorne un DataFrame con solamente los alumnos que han reprobado en la prestigiosa universidad. [0.3 puntos]
2. [ ]  `sort_top` que extraiga los n (parametrizable) alumnos destacados, ordenados de mayor a menor promedio. [0.3 puntos]

**Respuesta:**

In [20]:
def extract_failing(df: pd.DataFrame) -> pd.DataFrame:
    """Filtrar aquellos estudiantes que tengan mean_cl inferior a 4.0"""
    df_failing = df[df["mean_cl"] < 4.0]
    return df_failing


df_failing = extract_failing(df_cleaned)

In [21]:
def sort_top(df: pd.DataFrame, n: int) -> pd.DataFrame:
    # 1. Filtrar aquellos alumnos destacados: math_score_cl >= 6.0, writing_score_cl >= 6.3, reading_score_cl >= 6.3
    df_top = df[(df["math_score_cl"] >= 6.0) & (df["writing_score_cl"] >= 6.3) & (df["reading_score_cl"] >= 6.3)]

    # 2. Ordenar el dataframe por la columna mean_cl
    df_top_sorted = df_top.sort_values("mean_cl", ascending=False)

    # 3. Seleccionar los n mejores alumnos
    df_top_students = df_top_sorted.head(n)

    return df_top_students


df_top_students = sort_top(df_cleaned, n=10)

---

### 1.3.5 Padres Helicóptero 👨‍👩‍👧

Algunos padres (extremadamente entrometidos) preocupados por el desempeño de sus hijos, desean saber si estos han aprobado o no el año. Como la tarea de buscar a mano cada uno de estos alumnos en el `DataFrame` resulta demasiado tedioso, el rector le solicita crear una función de consulta. 

Cree una función que:

1. Reciba el `DataFrame` y una lista con nombres de alumnos
2. Extraiga las notas chilenas de matemáticas, escritura, lectura y promedio general (`mean_cl`) de los alumnos listados en `student_list` [0.3 puntos]
3. Genere una nueva columna transitoria `is_failing` (**asegurarse de no agregarla al dataframe original**) cuyo valor sea `True` si el alumno está reprobando o `False` en caso contrario [0.3 puntos]
4. Ordene por promedio chileno, de mayor a menor [0.2 puntos]
5. Reinicie el índice para que este comience desde 0 [0.2 puntos]


**Hint:** Puede serle de utilidad utilizar `isin()`. Recuerde además usar una copia del dataframe original para no modificarlo con la nueva columna.

**Respuesta:**

In [22]:
def query_students(df: pd.DataFrame, student_list: list[str]) -> pd.DataFrame:
    # 1. Se mantienen las columnas match_score_cl, writing_score_cl, reading_score_cl, mean_cl y rank
    df_students = df.copy()
    df_students = df[df["names"].isin(student_list)][
        ["names", "math_score_cl", "writing_score_cl", "reading_score_cl", "mean_cl"]
    ]

    # 2. Columna transitoria is_failing (True si mean_cl < 4.0, False en caso contrario)
    df_students["is_failing"] = df_students["mean_cl"] < 4.0

    # 3. Ordenar el dataframe por la columna mean_cl de mayor a menor
    df_students = df_students.sort_values("mean_cl", ascending=False)

    # 4. Reiniciar indices para que vayan de 0 a n-1
    df_students.reset_index(drop=True, inplace=True)

    return df_students

In [23]:
student_list = [
    "Lucille Stanphill",
    "Marcus Mcfarland",
    "Matthew Freeman",
    "Dana Mojica",
    "Paul Hyder",
    "Jeffrey Korn",
    "Robert Strain",
    "Ronald Jett",
    "Lorena Reed",
    "Hazel Posey",
]

df_query = query_students(df_cleaned, student_list)
df_query

,names,math_score_cl,writing_score_cl,reading_score_cl,mean_cl,is_failing
0,Paul Hyder,6.70,6.04,5.86,6.20,False
1,Lucille Stanphill,5.86,5.92,6.04,5.94,False
2,Marcus Mcfarland,4.78,4.96,4.84,4.86,False
3,Jeffrey Korn,5.20,4.06,4.36,4.54,False
4,Robert Strain,4.30,4.24,4.66,4.40,False
5,Matthew Freeman,4.12,3.76,3.94,3.94,True
6,Dana Mojica,3.34,3.76,4.12,3.74,True
7,Lorena Reed,3.16,3.58,4.18,3.64,True
8,Ronald Jett,3.52,3.04,3.34,3.30,True
9,Hazel Posey,2.44,2.62,3.28,2.78,True

---

### 1.3.6 Categorías de Rendimiento 📊

El rector, intrigado por saber si existe una relación entre el nivel educacional de los padres y las notas de sus hijos, les plantea estudiar dicha relación mediante categorización de los datos. 

Para esto, se les solicita que implementen la función `get_categories`, donde se generen dos series con diferentes tipos de categorización a partir de los promedios chilenos (`mean_cl`):

- Una con `pd.cut` con las labels `["B1", "B2", "B3", "B4", "B5"]` [0.2 Puntos]
- Otra con `pd.qcut`, con las labels `["Q1", "Q2", "Q3", "Q4", "Q5"]` [0.2 Puntos]

La función debe retornar una tupla con ambas series. Después, usando indexadores apropiados, agreguen a `df_cleaned` las columnas `cut_cl` y `qcut_cl`.

**Respuesta:**

In [24]:
# En esta celda implementa la operación solicitada
def get_categories(df: pd.DataFrame) -> tuple[pd.Series, pd.Series]:
    """Se generan 2 series con diferentes tipos de categorización a partir de los promedios 'mean_cl'ArithmeticError
    - Una con pd.cut con labels ['B1', 'B2', 'B3', 'B4', 'B5']
    - Otra con pd.qcut con labels ['Q1', 'Q2', 'Q3', 'Q4', 'Q5']
    """
    # pd.cut con labels ['B1', 'B2', 'B3', 'B4', 'B5']
    bins = [1, 2.2, 3.4, 4.6, 5.8, 7.0]
    labels_cut = ["B1", "B2", "B3", "B4", "B5"]
    categories_cut = pd.cut(df["mean_cl"], bins=bins, labels=labels_cut)

    # pd.qcut con labels ['Q1', 'Q2', 'Q3', 'Q4', 'Q5']
    labels_qcut = ["Q1", "Q2", "Q3", "Q4", "Q5"]
    categories_qcut = pd.qcut(df["mean_cl"], q=5, labels=labels_qcut)

    return categories_cut, categories_qcut

In [25]:
categorias_cut, categorias_qcut = get_categories(df_cleaned)
df_cleaned["cut_cl"] = categorias_cut
df_cleaned["qcut_cl"] = categorias_qcut

Hecho esto, grafique a través de un scatter plot el nivel educacional de los padres v/s el promedio chileno de los alumnos. Utilice los quintiles generados anteriormente (use la columna `qcut_cl`) para colorear los puntos y mostrar en qué quintil se encuentra cada dato.

**Pregunta: ❓** [0.3 Puntos]

> - ¿Qué diferencias hay entre las categorías generadas por `cut` y `qcut` (en términos conceptuales rangos-percentiles)?

**Respuesta 📝:**

```
Las categorías generadas por qcut representan cuantiles, en los cuales cada grupo tiene aproximadamente el mismo número de estudiantes, esto a su vez genera que los rangos de las notas para cada cuantil varien entre sí.

Por otro lado, cut simplemente divide por rangos fijos o umbrales definidos, sin considerar la distribución de las notas.
```

In [26]:
# Código para graficar
# Nota: asegúrese de que la columna qcut_cl esté creada antes de ejecutar esto

fig = px.scatter(
    df_cleaned.sort_values(by="mean_cl"),
    x="mean_cl",
    y="parental_level_of_education",
    hover_data=["gender"],
    color="qcut_cl",
    title="Promedio por Nivel de Educación de los Padres",
    labels={"mean_cl": "Promedio (Escala Chilena)", "parental_level_of_education": "Nivel Educacional de los Padres"},
    color_discrete_sequence=["tomato", "orange", "yellow", "greenyellow", "green"],
)

fig.show()

In [27]:
fig = px.scatter(
    df_cleaned.sort_values(by="mean_cl"),
    x="mean_cl",
    y="parental_level_of_education",
    hover_data=["gender"],
    color="cut_cl",
    title="Promedio por Nivel de Educación de los Padres",
    labels={"mean_cl": "Promedio (Escala Chilena)", "parental_level_of_education": "Nivel Educacional de los Padres"},
    color_discrete_sequence=["tomato", "orange", "yellow", "greenyellow", "green"],
)

fig.show()

**Pregunta: ❓** [0.3 Puntos]

> - ¿Es posible visualizar alguna tendencia en el gráfico?

**Respuesta 📝:**

```
En el grafico de qcut se pueden visualizar 2 tendencias:
1. A medida que aumenta el nivel de educación de los padres, las notas reprobatorias tienden a disminuir, por ejemplo, aquellos con padres que tienen un pregrado o magister ya no tienen notas bajo 3.0
2. A medida que disminuye el nivel de educación de los padres, las notas más altas de los estudiante se centran en notas más bajas, y por tanto, la densidad de las notas más altas se encuentra más alejada del 7.0.
```

---

# Conclusión

Cualquier duda del laboratorio, no duden en contactarnos por mail o U-cursos.

<p align="center">
  <img src="https://gifdb.com/images/high/orange-cat-cat-walking-with-two-legs-xlgf7qx4i24da74f.gif" width="400">
</p>